### PR TITLE
Add Thundercats

### LINKED ISSUE #1: Switch rx-flux for thundercats

### LINKED ISSUE #58: Fix linting errors

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
context stuff needs to be removed
cat render methods need to be implemented
fetch configuration needs to be implemented

closes #1
closes #58
closes #68

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
@morenoh149 rebased on qa. One more thing is still not working. Shpe image animation is not triggering. Once that is fixed can you QA it and merge if everything looks good. Should be no UI changes.

**Comment by morenoh149** [comment]
Shpe image animation works from my testing. Do you mean a particular platform/device?

**Comment by BerkeleyTrue** [comment]
In the context of this PR

**Comment by BerkeleyTrue** [comment]
@morenoh149 ready to merge once you give it a once over

**Pull request merged**
